name: "Podcast Generator"
author: "greyblood"
description: "Generate Podcast Feed from YAML File"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The Commiter's email address
    required: true
    default: ${{github.actor}}@localhost
  name:
    description: The Commiter's name
    required: true
    default: ${{github.actor}}